AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  SlackWebhookUrl:
    Type: String
  SlackChannelName:
    Type: String
  AwsAccountName:
    Type: String

Resources:
  SlackAwsBillingNotification:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: slack-aws-billing-notification
      CodeUri: src/handlers
      Handler: slackAwsBillingNotification.lambda_handler
      Runtime: python3.6
      Timeout: 900
      Events:
        DailyEvent:
          Type: Schedule
          Properties:
            Schedule: 'cron(0 0 * * ? *)'
      Policies:
        - AWSLambdaExecute
        - CloudWatchLogsFullAccess
        - CloudWatchReadOnlyAccess
      Environment:
        Variables:
          TZ: 'Asia/Tokyo'
          SlackWebhookUrl:
            Ref: SlackWebhookUrl
          SlackChannelName:
            Ref: SlackChannelName
          AwsAccountName:
            Ref: AwsAccountName
